// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using getbiz_getster_app;

namespace getbiz_getster_app.Migrations
{
    [DbContext(typeof(Getbizdb_DbContext))]
    partial class Getbizdb_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("getbiz_getster_app.getster_app_about_demo", b =>
                {
                    b.Property<int>("getster_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("getster_app_attachments_path")
                        .HasColumnType("longtext");

                    b.Property<string>("getster_app_demo_video_path")
                        .HasColumnType("longtext");

                    b.Property<string>("getster_app_time_stamp_description")
                        .HasColumnType("longtext");

                    b.Property<string>("getster_app_time_stamp_title")
                        .HasColumnType("longtext");

                    b.HasKey("getster_app_id");

                    b.ToTable("getster_app_about_demo");
                });

            modelBuilder.Entity("getbiz_getster_app.getster_app_audit_trail", b =>
                {
                    b.Property<int>("getster_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("getster_app_activity")
                        .HasColumnType("longtext");

                    b.Property<int>("getster_app_activity_by_getster_id")
                        .HasColumnType("int");

                    b.Property<string>("getster_app_activity_time_stamp")
                        .HasColumnType("longtext");

                    b.HasKey("getster_app_id");

                    b.ToTable("getster_app_audit_trail");
                });

            modelBuilder.Entity("getbiz_getster_app.getster_app_categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("getster_app_categories");
                });

            modelBuilder.Entity("getbiz_getster_app.getster_app_master", b =>
                {
                    b.Property<int>("getster_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("getster_app_development_status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("getster_app_icon_image")
                        .HasColumnType("longtext");

                    b.Property<string>("getster_app_icon_name")
                        .HasColumnType("longtext");

                    b.Property<string>("getster_app_web_link")
                        .HasColumnType("longtext");

                    b.HasKey("getster_app_id");

                    b.ToTable("getster_app_master");
                });

            modelBuilder.Entity("getbiz_getster_app.getster_app_names", b =>
                {
                    b.Property<int>("getster_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("getster_app_name")
                        .HasColumnType("longtext");

                    b.Property<string>("getster_app_title_bar_name")
                        .HasColumnType("longtext");

                    b.HasKey("getster_app_id");

                    b.ToTable("getster_app_names");
                });

            modelBuilder.Entity("getbiz_getster_app.getster_app_update_status", b =>
                {
                    b.Property<int>("getster_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("getster_app_update_time_stamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("getster_app_id");

                    b.ToTable("getster_app_update_status");
                });

            modelBuilder.Entity("getbiz_getster_app.getster_apps_and_categories_assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("getster_app_category_location")
                        .HasColumnType("float");

                    b.Property<int>("getster_app_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("getster_apps_and_categories_assignment");
                });
#pragma warning restore 612, 618
        }
    }
}
